(* ============================================================ *)
(*  ExtraTurnLevel.v                                            *)
(*                                                              *)
(*  CLAIM: The half-step gives an EXTRA LEVEL OF ROTATION.     *)
(*                                                              *)
(*  Classical 2D Euclidean plane:                               *)
(*    - Rotations form SO(2) ≅ S¹, generated by one angle θ.   *)
(*    - To return to identity: turn 360°.                      *)
(*    - The cyclic subgroup of order 2 is {0°, 180°} = Z/2Z.   *)
(*                                                              *)
(*  Triadic plane (I, N, F):                                    *)
(*    - Two distinct identities: id_I and id_N (refl_I, refl_N) *)
(*    - The half-step is a rotation that maps id_I → id_N.    *)
(*    - This rotation lives BETWEEN the two identities,         *)
(*      not on the original SO(2) circle.                       *)
(*    - To return to id_I: turn 360° AND apply half-step twice.*)
(*                                                              *)
(*  Net effect: total rotation group = SO(2) × Z/2Z.           *)
(*  The Z/2Z factor is the EXTRA LEVEL.                         *)
(*                                                              *)
(*  Geometric picture:                                          *)
(*    Classical:  S¹                                            *)
(*    Triadic:    S¹ × {I, N}  =  two stacked circles          *)
(*                connected by the half-step                     *)
(*                                                              *)
(*  Topologically: a double cover of the circle.                *)
(*  Algebraically: Spin(2) instead of SO(2).                    *)
(* ============================================================ *)

From Coq Require Import Arith Lia.

(* ============================================================ *)
(* Phases: I and N (omitting F for the rotation group)         *)
(* ============================================================ *)
Inductive Level : Type := LvlI | LvlN.

(* Half-step swaps levels — this IS the extra turn. *)
Definition flip (l : Level) : Level :=
  match l with LvlI => LvlN | LvlN => LvlI end.

(* ============================================================ *)
(* A triadic rotation: a classical angle PLUS a level.          *)
(* ============================================================ *)
Record TRot : Type := mkRot {
  angle : nat;   (* angle modulo 360 *)
  level : Level
}.

(* The classical identity. *)
Definition rot_id : TRot := mkRot 0 LvlI.

(* The half-step: rotate by 0°, but flip the level. *)
Definition half_step_rot (r : TRot) : TRot :=
  mkRot (angle r) (flip (level r)).

(* Compose two triadic rotations: add angles mod 360, XOR levels. *)
Definition compose_rot (r s : TRot) : TRot :=
  mkRot ((angle r + angle s) mod 360)
        (match level r, level s with
         | LvlI, x => x
         | x, LvlI => x
         | LvlN, LvlN => LvlI
         end).

(* ============================================================ *)
(* THE CORE FACTS                                               *)
(* ============================================================ *)

(* Fact 1: A full classical turn (360°) is NOT the identity     *)
(* if you arrived there via a half-step.                        *)
Theorem classical_turn_not_enough :
  let r := half_step_rot rot_id in
  r <> rot_id.
Proof.
  simpl. unfold rot_id. intro H.
  injection H. discriminate.
Qed.

(* Fact 2: Two half-steps DO return to the classical identity. *)
Theorem two_half_steps_return :
  half_step_rot (half_step_rot rot_id) = rot_id.
Proof.
  unfold rot_id, half_step_rot. simpl. reflexivity.
Qed.

(* Fact 3: A 360° rotation alone is not the identity if level=N. *)
(* The level component is INDEPENDENT of the angle component.   *)
Theorem level_is_independent_of_angle :
  forall theta,
  mkRot (theta mod 360) LvlN <> mkRot 0 LvlI.
Proof.
  intros theta H.
  injection H. intros Hl _. discriminate.
Qed.

(* Fact 4: To truly return to identity, you need BOTH:          *)
(*   - angle ≡ 0 (mod 360)   — classical condition              *)
(*   - level   = LvlI        — triadic condition                *)
Theorem identity_needs_both :
  forall r : TRot,
  r = rot_id <-> (angle r = 0 /\ level r = LvlI).
Proof.
  intro r. split.
  - intro H. rewrite H. split; reflexivity.
  - intros [Ha Hl].
    destruct r as [a l]. simpl in *.
    rewrite Ha, Hl. reflexivity.
Qed.

(* ============================================================ *)
(* THE EXTRA LEVEL: counting                                    *)
(*                                                              *)
(* In SO(2), the orbit of any rotation under <half-step> is     *)
(* either a singleton (classical) or a pair (triadic).          *)
(* The triadic rotation group has TWICE as many elements        *)
(* per angle.                                                    *)
(* ============================================================ *)

(* Every triadic rotation has a "partner" reachable by one      *)
(* half-step, and they are distinct.                            *)
Theorem every_rotation_has_partner : forall r : TRot,
  exists r', r' = half_step_rot r /\ r' <> r.
Proof.
  intro r. exists (half_step_rot r). split.
  - reflexivity.
  - destruct r as [a l]. unfold half_step_rot. simpl.
    intro H. injection H. intros Hl.
    destruct l; discriminate.
Qed.

(* The order of half_step is exactly 2. *)
Theorem half_step_order_two : forall r,
  half_step_rot (half_step_rot r) = r /\
  half_step_rot r <> r.
Proof.
  intro r. split.
  - destruct r as [a l]. unfold half_step_rot. simpl.
    destruct l; reflexivity.
  - destruct r as [a l]. unfold half_step_rot. simpl.
    intro H. injection H. intros Hl.
    destruct l; discriminate.
Qed.

(* ============================================================ *)
(* SUMMARY                                                      *)
(*                                                              *)
(* Classical rotation group:  SO(2)         = S¹               *)
(* Triadic rotation group:    SO(2) × Z/2Z  = S¹ × {I,N}       *)
(*                                                              *)
(* The Z/2Z factor IS the half-step.                            *)
(* It IS the extra level of turn.                               *)
(* It IS the same Z/2Z that appears as Spin → SO covers,       *)
(* as the deck transformation, as the dual reflexivity, and    *)
(* as the order-2 element of Z/2Z itself.                       *)
(* ============================================================ *)

Theorem extra_level_summary :
  (* The half-step is involutive (order 2). *)
  (forall r, half_step_rot (half_step_rot r) = r) /\
  (* But it is NOT the identity. *)
  (forall r, half_step_rot r <> r) /\
  (* The level is independent of the angle. *)
  (forall theta, mkRot (theta mod 360) LvlN <> mkRot 0 LvlI) /\
  (* Returning to identity requires angle=0 AND level=I. *)
  (forall r, r = rot_id <-> angle r = 0 /\ level r = LvlI).
Proof.
  split; [|split; [|split]].
  - intro r. apply (proj1 (half_step_order_two r)).
  - intro r. apply (proj2 (half_step_order_two r)).
  - apply level_is_independent_of_angle.
  - apply identity_needs_both.
Qed.

Print Assumptions extra_level_summary.
