/-
  TDLean.Operator.BCAlgebra -- the *-algebra generated by the prime shifts, and the
  Bost–Connes relations as an algebra presentation.

  The isometry part of the BC presentation (Bost–Connes 1995), in `Module.End ℂ (ℕ⁺ → ℂ)`
  where multiplication is composition:

      (BC1)  Sₙ* Sₙ = 1                            isometry
      (BC2)  Sₘ Sₙ = S₍ₘₙ₎                          semigroup
      (BC3)  Sₘ Sₙ* = Sₙ* Sₘ    whenever gcd(m,n) = 1   coprime commutation
      (BC0)  Sₙ Sₙ* ≠ 1                            NOT unitary

  **BC3 is the substantive one.** It is what makes `ℕˣ` act on the algebra the way BC needs,
  and it is sharp: `not_comm_of_not_coprime` shows it fails at `m = n = 2`. The proof is Gauss's
  lemma — `m ∣ nk` with `gcd(m,n) = 1` forces `m ∣ k` — so coprimality is doing real work, not
  bookkeeping.

  The `*` is realised by the inner product of `Ell2C`: `ip_shift_adjoint` and
  `ip_coshift_adjoint` together say the generating set `{Sₙ} ∪ {Sₙ*}` is closed under adjunction
  with respect to `⟪·,·⟫`, so `bcAlgebra` is a `*`-algebra in that sense.

  ## Honest scope

  Still no C\*-completion (this is a plain `ℂ`-subalgebra of endomorphisms, with no norm),
  no `ℂ[ℚ/ℤ]` factor, and no KMS states. The full BC algebra is `ℂ[ℚ/ℤ] ⋊ ℕˣ`; what is
  presented here is the `ℕˣ` half.
-/
import TDLean.Operator.Isometry

namespace TDLean.Operator

open TDLean.Zeta Complex

/-! ### Linearity -/

theorem shift_add (n : ℕ+) (f g : ℕ+ → ℂ) : shift n (f + g) = shift n f + shift n g := by
  funext k
  by_cases h : (n : ℕ) ∣ (k : ℕ)
  · obtain ⟨m, rfl⟩ : ∃ m : ℕ+, k = n * m := ⟨pdiv k n h, (mul_pdiv k n h).symm⟩
    simp [shift_apply_mul]
  · simp [shift_apply_of_not_dvd _ h]

theorem shift_smul (n : ℕ+) (c : ℂ) (f : ℕ+ → ℂ) : shift n (c • f) = c • shift n f := by
  funext k
  by_cases h : (n : ℕ) ∣ (k : ℕ)
  · obtain ⟨m, rfl⟩ : ∃ m : ℕ+, k = n * m := ⟨pdiv k n h, (mul_pdiv k n h).symm⟩
    simp [shift_apply_mul]
  · simp [shift_apply_of_not_dvd _ h]

theorem coshift_add (n : ℕ+) (f g : ℕ+ → ℂ) :
    coshift n (f + g) = coshift n f + coshift n g := rfl

theorem coshift_smul (n : ℕ+) (c : ℂ) (f : ℕ+ → ℂ) :
    coshift n (c • f) = c • coshift n f := rfl

/-! ### The generators, as algebra elements -/

/-- `Sₙ` as an endomorphism. -/
noncomputable def Sop (n : ℕ+) : Module.End ℂ (ℕ+ → ℂ) where
  toFun := shift n
  map_add' := shift_add n
  map_smul' := shift_smul n

/-- `Sₙ*` as an endomorphism. -/
noncomputable def Sadj (n : ℕ+) : Module.End ℂ (ℕ+ → ℂ) where
  toFun := coshift n
  map_add' := coshift_add n
  map_smul' := coshift_smul n

@[simp] theorem Sop_apply (n : ℕ+) (f : ℕ+ → ℂ) : Sop n f = shift n f := rfl
@[simp] theorem Sadj_apply (n : ℕ+) (f : ℕ+ → ℂ) : Sadj n f = coshift n f := rfl

/-! ### The semigroup law on sequences -/

theorem shift_shift (m n : ℕ+) (f : ℕ+ → ℂ) : shift m (shift n f) = shift (m * n) f := by
  funext j
  by_cases h : ((m * n : ℕ+) : ℕ) ∣ (j : ℕ)
  · obtain ⟨k, rfl⟩ : ∃ k : ℕ+, j = (m * n) * k := ⟨pdiv j (m * n) h, (mul_pdiv j (m * n) h).symm⟩
    rw [shift_apply_mul, show (m * n) * k = m * (n * k) by ring, shift_apply_mul,
      shift_apply_mul]
  · rw [shift_apply_of_not_dvd _ h]
    by_cases hm : (m : ℕ) ∣ (j : ℕ)
    · obtain ⟨k, rfl⟩ : ∃ k : ℕ+, j = m * k := ⟨pdiv j m hm, (mul_pdiv j m hm).symm⟩
      rw [shift_apply_mul]
      refine shift_apply_of_not_dvd _ ?_
      intro hn
      refine h ?_
      obtain ⟨c, rfl⟩ : ∃ c : ℕ+, k = n * c := ⟨pdiv k n hn, (mul_pdiv k n hn).symm⟩
      rw [PNat.mul_coe, PNat.mul_coe, PNat.mul_coe]
      exact ⟨(c : ℕ), by ring⟩
    · rw [shift_apply_of_not_dvd _ hm]

/-! ### BC3: coprime commutation, and its sharpness -/

/-- **BC3.** `Sₘ Sₙ* = Sₙ* Sₘ` when `gcd(m,n) = 1`. The proof is Gauss's lemma. -/
theorem shift_coshift_comm {m n : ℕ+} (h : Nat.Coprime (m : ℕ) (n : ℕ)) (f : ℕ+ → ℂ) :
    shift m (coshift n f) = coshift n (shift m f) := by
  funext k
  by_cases hm : (m : ℕ) ∣ (k : ℕ)
  · obtain ⟨j, rfl⟩ : ∃ j : ℕ+, k = m * j := ⟨pdiv k m hm, (mul_pdiv k m hm).symm⟩
    rw [shift_apply_mul, coshift, coshift, show n * (m * j) = m * (n * j) by ring,
      shift_apply_mul]
  · rw [shift_apply_of_not_dvd _ hm, coshift]
    refine (shift_apply_of_not_dvd _ ?_).symm
    intro hdvd
    refine hm ?_
    rw [PNat.mul_coe] at hdvd
    exact h.dvd_of_dvd_mul_left hdvd

/-- **BC3 is sharp.** At `m = n = 2` — not coprime — the relation fails. -/
theorem not_comm_of_not_coprime :
    shift 2 (coshift 2 (delta 1)) ≠ coshift 2 (shift 2 (delta 1)) := by
  rw [coshift_shift]
  exact shift_coshift_ne_id

/-! ### The star: the generating set is adjoint-closed -/

/-- The reverse adjoint identity `⟪Sₙ* f, g⟫ = ⟪f, Sₙ g⟫`. With `ip_shift_adjoint` this says
    `{Sₙ} ∪ {Sₙ*}` is closed under adjunction, so the generated algebra is a `*`-algebra. -/
theorem ip_coshift_adjoint (n : ℕ+) (f g : ℕ+ → ℂ) :
    ip (coshift n f) g = ip f (shift n g) := by
  have hinj : Function.Injective (fun m : ℕ+ => n * m) := fun a b hab => by
    simpa using mul_left_cancel hab
  have hzero : ∀ k ∉ Set.range (fun m : ℕ+ => n * m),
      (starRingEnd ℂ) (f k) * shift n g k = 0 := by
    intro k hk
    have hnd : ¬ (n : ℕ) ∣ (k : ℕ) := by
      intro hdvd
      exact hk ⟨pdiv k n hdvd, mul_pdiv k n hdvd⟩
    rw [shift_apply_of_not_dvd g hnd]
    simp
  have hmain := hinj.tsum_eq (Function.support_subset_iff'.mpr hzero)
  rw [ip, ip, ← hmain]
  exact tsum_congr fun m => by rw [shift_apply_mul, coshift]

/-! ### The BC relations, as an algebra presentation -/

/-- **BC1.** `Sₙ* Sₙ = 1`. -/
theorem bc_isometry (n : ℕ+) : Sadj n * Sop n = 1 := by
  ext f k
  simp [Module.End.mul_apply, coshift_shift]

/-- **BC2.** `Sₘ Sₙ = S₍ₘₙ₎`. -/
theorem bc_semigroup (m n : ℕ+) : Sop m * Sop n = Sop (m * n) := by
  ext f k
  simp [Module.End.mul_apply, shift_shift]

/-- **BC3.** `Sₘ Sₙ* = Sₙ* Sₘ` for `gcd(m,n) = 1`. -/
theorem bc_coprime {m n : ℕ+} (h : Nat.Coprime (m : ℕ) (n : ℕ)) :
    Sop m * Sadj n = Sadj n * Sop m := by
  ext f k
  simp only [Module.End.mul_apply, Sop_apply, Sadj_apply]
  rw [shift_coshift_comm h]

/-- **BC0.** `Sₙ Sₙ* ≠ 1`: the generators are isometries, not unitaries. -/
theorem bc_not_unitary : Sop 2 * Sadj 2 ≠ 1 := by
  intro h
  refine shift_coshift_ne_id ?_
  have := congrArg (fun T : Module.End ℂ (ℕ+ → ℂ) => T (delta 1)) h
  simpa [Module.End.mul_apply] using this

/-- The `*`-algebra generated by the prime shifts and their adjoints. -/
noncomputable def bcAlgebra : Subalgebra ℂ (Module.End ℂ (ℕ+ → ℂ)) :=
  Algebra.adjoin ℂ (Set.range Sop ∪ Set.range Sadj)

theorem Sop_mem (n : ℕ+) : Sop n ∈ bcAlgebra :=
  Algebra.subset_adjoin (Or.inl ⟨n, rfl⟩)

theorem Sadj_mem (n : ℕ+) : Sadj n ∈ bcAlgebra :=
  Algebra.subset_adjoin (Or.inr ⟨n, rfl⟩)

/-- The number operator is *not* in `bcAlgebra` as presented — it is the generator of the
    dynamics, adjoined separately. Recorded as the covariance relation instead. -/
theorem bcAlgebra_covariance (n : ℕ+) (f : ℕ+ → ℂ) :
    diag numberOp (Sop n f) = Sop n (fun m => (numberOp n + numberOp m) * f m) :=
  numberOp_covariance n f

end TDLean.Operator
