(* ================================================================= *)
(*  EventMonoidZeta.v  —  the arithmetic event-monoid and zeta as its   *)
(*  provenance-preserving compression.                                  *)
(*                                                                    *)
(*  Realizing the  mathematics = observation-preserving compression of  *)
(*  provenance  foundation (foundational-attempt.md) in number theory.  *)
(*  The dictionary:                                                     *)
(*                                                                    *)
(*    event-monoid / composition e2 o e1  <->  (N_{>0}, x, 1), atoms=primes *)
(*    provenance-preserving compression   <->  norm s n = n^{-s}        *)
(*    canonical / unique decomposition    <->  Euler product (FTA)      *)
(*    mark (persistent artifact)          <->  von Mangoldt Lambda      *)
(*    observation O(P)=O(M) (faithful)    <->  ln n = sum_{d|n} Lambda(d) *)
(*    partition function / compression    <->  zeta(s) = sum_n n^{-s}   *)
(*                                                                    *)
(*  What is PROVED here (each honest, no RH claim):                     *)
(*   A. the compression is a homomorphism: norm s (n*m) = norm s n *    *)
(*      norm s m  -- composition in the monoid maps to multiplication   *)
(*      of compressions.  This is the STRUCTURAL reason zeta factors.   *)
(*   B. each prime's sub-monoid {p^0,p^1,...} compresses to the         *)
(*      geometric factor 1/(1-p^{-s}); the product over prime atoms is  *)
(*      zeta(s) (s>1) -- unique factorization = the Euler product.      *)
(*   C. the mark reconstructs the observable: ln n = sum_{d|n} Lambda(d) *)
(*      -- the provenance (marks) faithfully gives the observation.     *)
(*                                                                    *)
(*  Axiom-clean (only the 4 standard classical-Reals axioms).           *)
(* ================================================================= *)

From Stdlib Require Import Reals Lra Lia.
Require Import VonMangoldtGlobal EulerProductZetaS.
Open Scope R_scope.

(* the provenance-preserving compression of the event-monoid: n |-> n^{-s} *)
Definition norm (s : R) (n : nat) : R := Rpower (INR n) (- s).

(* ----------------------------------------------------------------- *)
(*  A. the compression is a monoid homomorphism                       *)
(* ----------------------------------------------------------------- *)

Lemma Rpower_1_l : forall z, Rpower 1 z = 1.
Proof. intro z. unfold Rpower. rewrite ln_1, Rmult_0_r. apply exp_0. Qed.

(* the empty composition (identity event) compresses to 1 *)
Lemma norm_1 : forall s, norm s 1 = 1.
Proof. intro s. unfold norm. change (INR 1) with 1. apply Rpower_1_l. Qed.

(* THE homomorphism: composition n*m maps to product of compressions *)
Lemma norm_mul : forall s n m, (1 <= n)%nat -> (1 <= m)%nat ->
  norm s (n * m) = norm s n * norm s m.
Proof.
  intros s n m Hn Hm. unfold norm. rewrite mult_INR.
  symmetry. apply Rpower_mult_distr; apply lt_0_INR; lia.
Qed.

(* ----------------------------------------------------------------- *)
(*  B. canonical decomposition: prime sub-monoids -> Euler factors    *)
(* ----------------------------------------------------------------- *)

(* the sub-monoid generated by a single atom p : norm is a pure power *)
Lemma norm_prime_pow : forall s p k, (1 <= p)%nat ->
  norm s (p ^ k) = (norm s p) ^ k.
Proof.
  intros s p k Hp. unfold norm. rewrite pow_INR.
  induction k as [| k IH]; [ change ((INR p)^0) with 1; simpl; apply Rpower_1_l | ].
  cbn [pow]. rewrite <- IH.
  rewrite Rpower_mult_distr; [ reflexivity | apply lt_0_INR; lia | ].
  apply pow_lt; apply lt_0_INR; lia.
Qed.

Lemma norm_eq_Rpower : forall s p, norm s p = Rpower (INR p) (- s).
Proof. reflexivity. Qed.

(* the compression of the prime sub-monoid {p^0, p^1, ...} is geometric:
   sum_k (p^k)^{-s} = 1/(1 - p^{-s})  -- the Euler factor for the atom p *)
Theorem prime_submonoid_geometric : forall (p : nat) (s : R),
  (2 <= p)%nat -> 0 < s ->
  Un_cv (fun K => sum_f_R0 (fun k => norm s (p ^ k)) K) (/ (1 - norm s p)).
Proof.
  intros p s Hp Hs.
  assert (Hp2 : 2 <= INR p) by (replace 2 with (INR 2) by (simpl; ring); apply le_INR; lia).
  apply (Un_cv_ext (fun K => sum_f_R0 (fun k => (Rpower (INR p) (- s)) ^ k) K)).
  - intro K. apply sum_eq. intros i _.
    rewrite (norm_prime_pow s p i) by lia. rewrite norm_eq_Rpower. reflexivity.
  - rewrite norm_eq_Rpower. apply euler_factor_s; [ exact Hs | exact Hp2 ].
Qed.

(* ----------------------------------------------------------------- *)
(*  C. the mark reconstructs the observable (O(P) = O(M))             *)
(* ----------------------------------------------------------------- *)

(* the observable log-size of a composite = sum of the marks of its      *)
(* divisors: the provenance (Lambda-marks) faithfully gives ln n.        *)
Theorem provenance_additive : forall n, (1 <= n)%nat -> ln (INR n) = dsum Lam n.
Proof. intros n Hn. symmetry. apply vonmangoldt_identity; exact Hn. Qed.

(* ----------------------------------------------------------------- *)
(*  the event-monoid / zeta-compression picture, bundled              *)
(* ----------------------------------------------------------------- *)

Theorem event_monoid_zeta_compression : forall s, 0 < s ->
  (* A. compression preserves composition (identity + homomorphism) *)
  (norm s 1 = 1)
  /\ (forall n m, (1 <= n)%nat -> (1 <= m)%nat -> norm s (n * m) = norm s n * norm s m)
  (* B. canonical decomposition: each prime atom's sub-monoid is geometric *)
  /\ (forall p k, (1 <= p)%nat -> norm s (p ^ k) = (norm s p) ^ k)
  /\ (forall p, (2 <= p)%nat ->
        Un_cv (fun K => sum_f_R0 (fun k => norm s (p ^ k)) K) (/ (1 - norm s p)))
  (* C. the mark reconstructs the observable: ln n = sum_{d|n} Lambda(d) *)
  /\ (forall n, (1 <= n)%nat -> ln (INR n) = dsum Lam n).
Proof.
  intros s Hs.
  split; [ apply norm_1 | ].
  split; [ intros n m Hn Hm; apply norm_mul; assumption | ].
  split; [ intros p k Hp; apply norm_prime_pow; exact Hp | ].
  split; [ intros p Hp; apply prime_submonoid_geometric; [ exact Hp | exact Hs ] | ].
  intros n Hn; apply provenance_additive; exact Hn.
Qed.

Print Assumptions event_monoid_zeta_compression.
