(* ================================================================= *)
(*  LogBaseChange.v  --  change of base for logarithms, and what      *)
(*                       base 10 actually contributes.                *)
(*                                                                    *)
(*  The question this answers: how do log_10 pi, log_10 e, ln pi and   *)
(*  log_pi e relate to one another?                                    *)
(*                                                                    *)
(*  Answer, made machine-checked here: they are NOT four independent   *)
(*  quantities.  The whole family is generated by ln pi and ln 10,     *)
(*  and every relation among them is pure change of base --            *)
(*  logb_change -- with no arithmetic content whatsoever.              *)
(*                                                                    *)
(*  And base 10 carries no number-theoretic significance: ln10_split   *)
(*  records that its ENTIRE prime content is 10 = 2 * 5.  Base ten is  *)
(*  a hand-counting convention, not a fact about the integers.         *)
(*                                                                    *)
(*  The one constant here that IS a prime object is ln pi.  That is    *)
(*  proved in LnPiPrimes.v, not here.                                  *)
(* ================================================================= *)

From Stdlib Require Import Reals Lra.
Require Import CertifiedPi LnConstants.
Open Scope R_scope.

Definition logb (b x : R) : R := ln x / ln b.

(* ----------------------------------------------------------------- *)
(*  0.  positivity of ln b for b > 1 -- the denominators              *)
(* ----------------------------------------------------------------- *)

Lemma ln_gt0 : forall b, 1 < b -> 0 < ln b.
Proof.
  intros b Hb. rewrite <- ln_1. apply ln_increasing; lra.
Qed.

Lemma ln_ne0 : forall b, 1 < b -> ln b <> 0.
Proof. intros b Hb; apply Rgt_not_eq, ln_gt0; exact Hb. Qed.

Lemma one_lt_PI : 1 < PI.
Proof. pose proof PI_lower as H; lra. Qed.

Lemma lnPI_gt0 : 0 < ln PI.
Proof. apply ln_gt0, one_lt_PI. Qed.

Lemma lnPI_ne0 : ln PI <> 0.
Proof. apply ln_ne0, one_lt_PI. Qed.

Lemma ln10_ne0 : ln 10 <> 0.
Proof. apply ln_ne0; lra. Qed.

(* ----------------------------------------------------------------- *)
(*  1.  base 10 contributes exactly 2 * 5, and nothing else           *)
(* ----------------------------------------------------------------- *)

Theorem ln10_split : ln 10 = ln 2 + ln 5.
Proof.
  replace 10 with (2 * 5) by ring. apply ln_mult; lra.
Qed.

(* ----------------------------------------------------------------- *)
(*  2.  change of base -- the single relation generating them all     *)
(* ----------------------------------------------------------------- *)

Theorem logb_change : forall b c x, 1 < b -> 1 < c -> 0 < x ->
  logb b x = logb b c * logb c x.
Proof.
  intros b c x Hb Hc Hx. unfold logb.
  field; split; [ apply ln_ne0; exact Hc | apply ln_ne0; exact Hb ].
Qed.

(* ----------------------------------------------------------------- *)
(*  3.  the four constants of the question                           *)
(* ----------------------------------------------------------------- *)

(* log_pi e = 1 / ln pi : the reciprocal, nothing more *)
Theorem logPI_e_inv : logb PI (exp 1) = / ln PI.
Proof.
  unfold logb. rewrite ln_exp. field. exact lnPI_ne0.
Qed.

Theorem lnPI_logPI_e : ln PI * logb PI (exp 1) = 1.
Proof.
  rewrite logPI_e_inv. field. exact lnPI_ne0.
Qed.

(* log_10 pi * log_pi e = log_10 e *)
Theorem log10_e_factor : logb 10 PI * logb PI (exp 1) = logb 10 (exp 1).
Proof.
  symmetry. apply logb_change; [ lra | apply one_lt_PI | apply exp_pos ].
Qed.

(* log_10 pi / log_10 e = ln pi *)
Theorem logPI_of_ratio : logb 10 PI / logb 10 (exp 1) = ln PI.
Proof.
  unfold logb. rewrite ln_exp. field. exact ln10_ne0.
Qed.

(* ln pi = log_10 pi * ln 10, i.e. base 10 is a rescaling by ln 2 + ln 5 *)
Theorem lnPI_from_log10 : ln PI = logb 10 PI * (ln 2 + ln 5).
Proof.
  rewrite <- ln10_split. unfold logb. field. exact ln10_ne0.
Qed.

(* ----------------------------------------------------------------- *)
(*  4.  the collapse, stated once                                    *)
(* ----------------------------------------------------------------- *)

(* Only TWO of the four are independent.  Given ln pi and ln 10, the   *)
(* other three are determined -- no number theory is involved in any   *)
(* of these passages.                                                 *)
Theorem four_constants_collapse :
  logb 10 PI      = ln PI / (ln 2 + ln 5)
  /\ logb 10 (exp 1) = / (ln 2 + ln 5)
  /\ logb PI (exp 1) = / ln PI
  /\ logb 10 PI * logb PI (exp 1) = logb 10 (exp 1).
Proof.
  assert (H10 : ln 2 + ln 5 <> 0) by (rewrite <- ln10_split; exact ln10_ne0).
  repeat split.
  - rewrite <- ln10_split. reflexivity.
  - unfold logb. rewrite ln_exp, <- ln10_split. field. exact ln10_ne0.
  - exact logPI_e_inv.
  - exact log10_e_factor.
Qed.

Print Assumptions logb_change.
Print Assumptions four_constants_collapse.

(* ================================================================= *)
(*  END LogBaseChange.v                                               *)
(* ================================================================= *)
