(* ================================================================= *)
(*  ProductFormulaQ.v                                                *)
(*                                                                    *)
(*  THE PRODUCT FORMULA OVER Q  --  the adelic bridge, stated at the   *)
(*  one level where it costs NO axioms: the rational level.           *)
(*                                                                    *)
(*  For a nonzero rational x, the places v of Q (the archimedean       *)
(*  place infinity and one non-archimedean place per prime p) satisfy  *)
(*                                                                    *)
(*        prod_v  |x|_v  =  1        (Ostrowski / product formula)     *)
(*                                                                    *)
(*  i.e.  |x|_infinity  =  1 / prod_p |x|_p :  the ARCHIMEDEAN size of  *)
(*  a rational is RECONSTRUCTED from its finitely many p-adic          *)
(*  valuations.  For a POSITIVE INTEGER n this is exactly unique       *)
(*  factorization  n = prod_p p^{v_p(n)}  (so |n|_inf = n reconstructs  *)
(*  as prod_p p^{v_p}); for a positive rational a/b it is the quotient  *)
(*  of the two integer instances.                                     *)
(*                                                                    *)
(*  THE POINT (re: can profinite / adelic completion bridge to R       *)
(*  without the full R machinery?).  This file shows the honest        *)
(*  answer: for RATIONAL inputs you never need R -- the archimedean     *)
(*  absolute value of a rational IS a rational and is determined by     *)
(*  finite data, provable entirely in Q, AXIOM-FREE.  What CANNOT be    *)
(*  reached this way is R itself:  R = Q_infinity is the COMPLETION at   *)
(*  the archimedean place, a separate factor of the adele ring          *)
(*    A_Q = R x A_f ,   A_f = (prod_p Z_p) tensor Q ,                  *)
(*  orthogonal to -- and not generated by -- the finite/profinite tower *)
(*  prod_p Z_p = lim Z/nZ.  The product formula ties the places         *)
(*  together on rational points; the completion to R (hence Gamma-       *)
(*  factors, zeta special values, the functional equation) lives at the *)
(*  place infinity and is irreducibly real/complex.  See the closing    *)
(*  note for exactly where the axioms would re-enter.                  *)
(*                                                                    *)
(*  Reuses: code / code_surj (PrimeFactorizationExists) -- factorization *)
(*  existence over the first n primes; qpow (PrimonGas); primes_upto     *)
(*  (redefined locally to stay Reals-free).                            *)
(*                                                                    *)
(*  Axiom-free: constructive Z/nat + Q (Closed under the global ctx).  *)
(* ================================================================= *)

Require Import PrimeFactorizationN.
Require Import PrimeFactorizationExists.
Require Import PrimonGas.
From Stdlib Require Import ZArith Znumtheory QArith Lqa Lia List.
Import ListNotations.
Open Scope Q_scope.

(* ----------------------------------------------------------------- *)
(*  Q-arithmetic plumbing                                            *)
(* ----------------------------------------------------------------- *)

(* inject_Z of a nonzero integer is a nonzero rational *)
Lemma injZ_nonzero : forall z, (z <> 0)%Z -> ~ inject_Z z == 0.
Proof. intros z Hz Heq; apply Hz; unfold Qeq in Heq; simpl in Heq; lia. Qed.

(* a power of a nonzero rational is nonzero *)
Lemma qpow_nonzero : forall x k, ~ x == 0 -> ~ qpow x k == 0.
Proof.
  intros x k Hx; induction k as [|k IH]; cbn [qpow].
  - intro H; unfold Qeq in H; simpl in H; discriminate.
  - intro H; destruct (Qmult_integral _ _ H); [ apply Hx | apply IH ]; assumption.
Qed.

(* inject_Z commutes with taking a (natural) power: Z-power <-> qpow *)
Lemma inject_Z_pow : forall p k, inject_Z (p ^ Z.of_nat k) == qpow (inject_Z p) k.
Proof.
  intros p k; induction k as [|k IH].
  - replace (Z.of_nat 0) with 0%Z by reflexivity.
    rewrite Z.pow_0_r; reflexivity.
  - rewrite Nat2Z.inj_succ, Z.pow_succ_r by lia.
    rewrite inject_Z_mult, IH; cbn [qpow]; reflexivity.
Qed.

(* ----------------------------------------------------------------- *)
(*  THE FINITE-ADELIC ABSOLUTE-VALUE PRODUCT                         *)
(*                                                                    *)
(*  For n = code ps ks = prod_i (ps_i)^(ks_i), the product of the      *)
(*  non-archimedean absolute values is                                *)
(*     prod_p |n|_p  =  prod_i (ps_i)^(-ks_i)  =  fabs ps ks.          *)
(* ----------------------------------------------------------------- *)

Fixpoint fabs (ps : list Z) (ks : list nat) : Q :=
  match ps, ks with
  | p :: ps', k :: ks' => / qpow (inject_Z p) k * fabs ps' ks'
  | _, _ => 1
  end.

(* ----------------------------------------------------------------- *)
(*  THE PRODUCT FORMULA FOR A POSITIVE INTEGER                       *)
(*     |n|_infinity * prod_p |n|_p  =  n * prod_p p^{-v_p(n)}  =  1     *)
(* ----------------------------------------------------------------- *)

Lemma pf_int : forall ps ks, Forall prime ps -> length ps = length ks ->
  inject_Z (code ps ks) * fabs ps ks == 1.
Proof.
  induction ps as [|p ps' IH]; intros ks Hpr Hlen.
  - cbn [code fabs]; replace (inject_Z 1) with 1 by reflexivity; ring.
  - destruct ks as [|k ks']; [ simpl in Hlen; lia | ].
    inversion Hpr as [| ? ? Hp Hpr']; subst.
    cbn [code fabs].
    rewrite inject_Z_mult, inject_Z_pow.
    assert (Hq : ~ qpow (inject_Z p) k == 0)
      by (apply qpow_nonzero, injZ_nonzero; destruct Hp as [Hp1 _]; lia).
    setoid_replace
      (qpow (inject_Z p) k * inject_Z (code ps' ks')
         * (/ qpow (inject_Z p) k * fabs ps' ks'))
      with
      ((qpow (inject_Z p) k * / qpow (inject_Z p) k)
         * (inject_Z (code ps' ks') * fabs ps' ks'))
      by ring.
    rewrite (Qmult_inv_r _ Hq), Qmult_1_l.
    apply IH; [ exact Hpr' | simpl in Hlen; lia ].
Qed.

(* ----------------------------------------------------------------- *)
(*  EXISTENCE: every positive integer HAS such a representation       *)
(*  (via code_surj over the primes up to n), so the formula is not     *)
(*  vacuous -- it holds for every actual integer.                     *)
(* ----------------------------------------------------------------- *)

(* the primes <= B, as a Z-list (local copy, keeps this file Reals-free) *)
Definition primes_upto (B : nat) : list Z :=
  filter (fun z => if prime_dec z then true else false)
         (map Z.of_nat (seq 0 (S B))).

Lemma primes_upto_Forall : forall B, Forall prime (primes_upto B).
Proof.
  intro B; apply Forall_forall; intros q Hq; unfold primes_upto in Hq.
  apply filter_In in Hq; destruct Hq as [_ Hf].
  destruct (prime_dec q) as [Hp | _]; [ exact Hp | discriminate ].
Qed.

Lemma NoDup_map_inj : forall (A B : Type) (f : A -> B) (l : list A),
  (forall x y, In x l -> In y l -> f x = f y -> x = y) -> NoDup l -> NoDup (map f l).
Proof.
  intros A B f l; induction l as [|a l IH]; intros Hinj Hnd; simpl; [ constructor | ].
  rewrite NoDup_cons_iff in Hnd; destruct Hnd as [Hna Hnd].
  rewrite NoDup_cons_iff; split.
  - intro Hin; apply in_map_iff in Hin; destruct Hin as [y [Hfy Hy]].
    assert (a = y) by (apply Hinj; [ left; reflexivity | right; exact Hy | symmetry; exact Hfy ]).
    subst y; contradiction.
  - apply IH; [ intros x y Hx Hy; apply Hinj; right; assumption | exact Hnd ].
Qed.

Lemma primes_upto_nodup : forall B, NoDup (primes_upto B).
Proof.
  intro B; unfold primes_upto; apply NoDup_filter.
  apply NoDup_map_inj; [ intros x y _ _ H; apply Nat2Z.inj; exact H | apply seq_NoDup ].
Qed.

Lemma primes_upto_complete : forall B q,
  prime q -> (q <= Z.of_nat B)%Z -> In q (primes_upto B).
Proof.
  intros B q Hp Hq; unfold primes_upto; apply filter_In.
  assert (Hq2 : (2 <= q)%Z) by (destruct Hp; lia).
  split.
  - apply in_map_iff; exists (Z.to_nat q); split.
    + apply Z2Nat.id; lia.
    + apply in_seq; split; [ lia | ].
      assert (Z.to_nat q <= B)%nat
        by (apply (proj2 (Nat2Z.inj_le (Z.to_nat q) B));
              rewrite Z2Nat.id by lia; exact Hq); lia.
  - destruct (prime_dec q) as [_ | Hnp]; [ reflexivity | contradiction ].
Qed.

Corollary product_formula_int : forall n, (0 < n)%Z ->
  exists ps ks,
       Forall prime ps
    /\ length ps = length ks
    /\ code ps ks = n                              (* n = prod_p p^{v_p(n)} *)
    /\ inject_Z n * fabs ps ks == 1.               (* |n|_inf * prod_p |n|_p = 1 *)
Proof.
  intros n Hn.
  set (B := Z.to_nat n).
  assert (Hsm : forall q, prime q -> (q | n)%Z -> In q (primes_upto B)).
  { intros q Hq Hqn.
    apply primes_upto_complete; [ exact Hq | ].
    unfold B; rewrite Z2Nat.id by lia.
    apply Z.divide_pos_le; [ exact Hn | exact Hqn ]. }
  destruct (code_surj (primes_upto B) (primes_upto_Forall B) (primes_upto_nodup B)
              n Hn Hsm) as [ks [Hlen Hcode]].
  exists (primes_upto B), ks.
  repeat split; [ apply primes_upto_Forall | exact Hlen | exact Hcode | ].
  rewrite <- Hcode; apply pf_int; [ apply primes_upto_Forall | exact Hlen ].
Qed.

(* ----------------------------------------------------------------- *)
(*  THE PRODUCT FORMULA FOR A POSITIVE RATIONAL                      *)
(*                                                                    *)
(*  Write x = a / b with a = code ps ea, b = code ps eb over a common   *)
(*  prime list ps (existence for both a and b from code_surj over      *)
(*  primes_upto of a*b).  Then                                        *)
(*     |x|_infinity          = inject_Z a / inject_Z b                 *)
(*     prod_p |x|_p          = (prod_p |a|_p) / (prod_p |b|_p)          *)
(*                          = fabs ps ea / fabs ps eb                  *)
(*  and their product is 1 -- the quotient of the two integer          *)
(*  instances (pf_int for a and for b).                               *)
(* ----------------------------------------------------------------- *)

Theorem product_formula_Q : forall ps ea eb,
  Forall prime ps -> length ps = length ea -> length ps = length eb ->
  (inject_Z (code ps ea) / inject_Z (code ps eb))     (* |x|_infinity, x = a/b *)
    * (fabs ps ea / fabs ps eb)                        (* prod_p |x|_p          *)
    == 1.
Proof.
  intros ps ea eb Hpr Hla Hlb.
  pose proof (pf_int ps ea Hpr Hla) as Pa.
  pose proof (pf_int ps eb Hpr Hlb) as Pb.
  set (Za := inject_Z (code ps ea)) in *.
  set (Zb := inject_Z (code ps eb)) in *.
  set (Fa := fabs ps ea) in *.
  set (Fb := fabs ps eb) in *.
  assert (Hrw : (Za / Zb) * (Fa / Fb) == (Za * Fa) * / (Zb * Fb)).
  { unfold Qdiv; rewrite Qinv_mult_distr; ring. }
  rewrite Hrw, Pa, Pb; now rewrite Qmult_1_l.
Qed.

Print Assumptions product_formula_int.
Print Assumptions product_formula_Q.

(* ================================================================= *)
(*  MASTER THEOREM                                                   *)
(* ================================================================= *)

Theorem product_formula :
  (* INTEGER: every positive integer factors, and its archimedean size  *)
  (* is the reciprocal of the product of its p-adic absolute values     *)
  (forall n, (0 < n)%Z -> exists ps ks,
      Forall prime ps /\ length ps = length ks
      /\ code ps ks = n /\ inject_Z n * fabs ps ks == 1)
  (* RATIONAL: for x = a/b over a common prime list, prod_v |x|_v = 1    *)
  /\ (forall ps ea eb, Forall prime ps ->
        length ps = length ea -> length ps = length eb ->
        (inject_Z (code ps ea) / inject_Z (code ps eb))
          * (fabs ps ea / fabs ps eb) == 1).
Proof.
  split; [ exact product_formula_int | exact product_formula_Q ].
Qed.

Print Assumptions product_formula.

(* ================================================================= *)
(*  END ProductFormulaQ.v                                            *)
(*                                                                    *)
(*  WHERE THE AXIOMS WOULD RE-ENTER (the honest ceiling).            *)
(*  Everything above is over Q / Z and is AXIOM-FREE, because for a    *)
(*  rational input the archimedean absolute value |x|_inf is itself a   *)
(*  rational number (here a ratio of two coded integers).  The bridge   *)
(*  is: finite valuations DETERMINE archimedean size on rational        *)
(*  points.  It does NOT build R.  R = Q_infinity is the metric         *)
(*  COMPLETION at the archimedean place; obtaining it (Cauchy sequences /*)
(*  Dedekind cuts) is exactly where classical logic (LEM on reals,      *)
(*  the completeness axiom) enters -- the quarantined axioms of the     *)
(*  repo's Reals files.  The finite/profinite side  prod_p Z_p =        *)
(*  lim Z/nZ  and the finite adeles are inverse limits of finite        *)
(*  objects and stay constructive; but they are a SEPARATE factor of    *)
(*  A_Q = R x A_f and never generate the archimedean place.  Hence      *)
(*  Gamma-factors, the completed xi(s) = pi^{-s/2}Gamma(s/2)zeta(s), the *)
(*  functional equation s <-> 1-s, and zeta special values (pi^2/6)     *)
(*  are archimedean-local and remain out of reach of this bridge --      *)
(*  they need R/C, not the profinite completion.                       *)
(*                                                                    *)
(*  Closed under the global context (axiom-free).                    *)
(* ================================================================= *)
